# Generated by Django 3.2.7 on 2021-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
