# Generated by Django 3.2.7 on 2021-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='number_of_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
