# Generated by Django 3.2.7 on 2021-10-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20211001_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='liked',
        ),
    ]
